- name: Localhost
  hosts: localhost

  vars:
    - myself_email: '{{ myself_email_vault }}'
    - gmail_sender: '{{ gmail_sender_vault }}'
    - gmail_sender_pass: '{{ gmail_sender_pass_vault }}'

  vars_files:
    - secrets.yml

  handlers:
    - name: Generate aliases
      command: newaliases

    - name: Restart postfix
      command: systemctl restart postfix.service

  tasks:
    - name: Remove unwanted packages
      apt:
        name: '{{ item }}'
        state: absent
        purge: yes
      loop:
        - unattended-upgrades
        - apt-listchanges
        - exim4

    - name: Swappiness
      sysctl:
        name: vm.swappiness
        value: '1'
        state: present

    - name: Set timezone to Europe/Helsinki
      timezone:
        name: Europe/Helsinki
      notify: reboot

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install packages
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - ntp
        - heirloom-mailx
        - sqlite
        - libffi-dev
        - libssl-dev
        - wiringpi
        - make
        - build-essential
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - postfix
        - mailutils

    - name: Add pi to aliases
      lineinfile:
        path: /etc/aliases
        regexp: '^pi:'
        line: 'pi: root'
      notify: Generate aliases

    - name: Add myself to aliases
      lineinfile:
        path: /etc/aliases
        regexp: '^root:'
        line: 'root: {{ myself_email }}'
      notify: Generate aliases

    - name: Create /etc/postfix/sasl_passwd
      template:
        src: sasl_passwd
        dest: /etc/postfix/sasl_passwd
        owner: root
        group: root
        mode: u=rw,g=,o=
      register: sasl_password

    - name: postmap /etc/postfix/sasl_passwd
      command: postmap /etc/postfix/sasl_passwd
      notify: Restart postfix
      when: sasl_password.changed

    - name: Postfix config
      blockinfile:
        path: /etc/postfix/main.cf
        block: |
          relayhost = [smtp.gmail.com]:587
          smtp_use_tls = yes
          smtp_sasl_auth_enable = yes
          smtp_sasl_security_options =
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

    - name: Apt autoremove
      apt:
        autoremove: yes
        purge: yes

    - name: Apt autoclean
      apt:
        autoclean: yes
