- name: For all
  hosts: localhost

  vars:
    - myself_email: '{{ myself_email_vault }}'
    - gmail_sender: '{{ gmail_sender_vault }}'
    - gmail_sender_pass: '{{ gmail_sender_pass_vault }}'

  vars_files:
    - secrets.yml

  handlers:
    - name: Generate aliases
      command: newaliases

    - name: Restart postfix
      command: systemctl restart postfix.service

  tasks:
    - include: tasks/for_all.yml

- name: For gin
  hosts: gin
  tasks:
    - include: tasks/for_gin.yml

- name: For all post tasks
  hosts: localhost
  tasks:
    - name: Apt autoremove
      apt:
        autoremove: yes
        purge: yes

    - name: Apt autoclean
      apt:
        autoclean: yes
