- name: Localhost
  hosts: localhost

  vars:
    - myself_email: '{{ myself_email_vault }}'

  vars_files:
    - secrets.yml

  handlers:
    - name: Generate aliases
      command: newaliases

  tasks:
    - name: Remove unwanted packages
      apt:
        name: '{{ item }}'
        state: absent
        purge: yes
      loop:
        - unattended-upgrades
        - apt-listchanges
        - exim4

    - name: Swappiness
      sysctl:
        name: vm.swappiness
        value: '1'
        state: present

    - name: Set timezone to Europe/Helsinki
      timezone:
        name: Europe/Helsinki
      notify: reboot

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install packages
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - ntp
        - heirloom-mailx
        - sqlite
        - libffi-dev
        - libssl-dev
        - wiringpi
        - make
        - build-essential
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - postfix
        - mailutils

    - name: Add pi to aliases
      lineinfile:
        path: /etc/aliases
        regexp: '^pi:'
        line: 'pi: root'
      notify: Generate aliases

    - name: Add myself to aliases
      lineinfile:
        path: /etc/aliases
        regexp: '^root:'
        line: 'root: {{ myself_email }}'
      notify: Generate aliases

    - name: Apt autoremove
      apt:
        autoclean: yes
        autoremove: yes
        purge: yes
